from __future__ import annotations

import json
import os
import re
from typing import Dict

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

from ..llm import build_rewrite_prompt
from ..models import CodeRecord, RewriteCandidate
from .base import ExpertCandidateGenerator
from .config import ExpertConfig


class LocalTransformersGenerator(ExpertCandidateGenerator):
    def __init__(
        self,
        model_path: str,
        tokenizer=None,
        model=None,
        max_new_tokens: int = 512,
        temperature: float = 0.2,
        top_p: float = 0.9,
        load_in_4bit: bool = True,
    ):
        self.max_new_tokens = max_new_tokens
        self.base_temperature = temperature
        self.top_p = top_p

        if model is not None and tokenizer is not None:
            self.model = model
            self.tokenizer = tokenizer
            print("✅ 生成器复用已有模型（共享权重）")
            return

        print("加载生成器模型...")
        if load_in_4bit:
            quant_config = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_compute_dtype=torch.float16,
                bnb_4bit_use_double_quant=True,
            )
        else:
            quant_config = None

        self.tokenizer = AutoTokenizer.from_pretrained(
            model_path, trust_remote_code=True
        )
        self.model = AutoModelForCausalLM.from_pretrained(
            model_path,
            quantization_config=quant_config,
            device_map="auto",
            trust_remote_code=True,
        ).eval()
        print("✅ 生成器模型加载完成")

    def generate(self, expert: ExpertConfig, record: CodeRecord) -> RewriteCandidate:
        temp_map = {
            "cot": 0.4,
            "style": 0.6,
            "ast": 0.3,
            "variable": 0.7,
            "control_flow": 0.5,
        }
        temperature = temp_map.get(expert.strategy, self.base_temperature)

        system_prompt = (
            "你是一个专业的代码改写助手。\n"
            "只输出 JSON 格式结果，不要有其他文字。"
        )

        prompt = build_rewrite_prompt(record, expert.strategy, feedback="")

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt},
        ]

        text = self.tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )

        inputs = self.tokenizer(text, return_tensors="pt").to(self.model.device)

        with torch.inference_mode():
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=self.max_new_tokens,
                temperature=temperature,
                top_p=self.top_p,
                do_sample=True,
                pad_token_id=self.tokenizer.eos_token_id,
            )

        response = self.tokenizer.decode(
            outputs[0][inputs.input_ids.shape[1]:],
            skip_special_tokens=True,
        )

        code = record.code
        reasoning = record.reasoning
        rationale = "Fallback to original"

        try:
            json_match = re.search(r'\{[^{}]*\}', response, re.DOTALL)
            if json_match:
                data = json.loads(json_match.group())
                code = data.get("code", record.code)
                reasoning = data.get("reasoning", record.reasoning)
                rationale = data.get("rationale", f"Generated by {expert.strategy}")
            else:
                code_match = re.search(r'```python\s*(.*?)\s*```', response, re.DOTALL)
                if code_match:
                    code = code_match.group(1).strip()
                    rationale = "Parsed from code block"
                else:
                    if "def " in response or "class " in response:
                        code = response.strip()
                        rationale = "Parsed from raw response"
        except Exception as e:
            print(f"解析失败: {e}")

        if code.strip() == record.code.strip():
            code = record.code + f"\n# {expert.strategy} rewrite\n"

        return RewriteCandidate(
            code=code,
            reasoning=reasoning,
            rationale=rationale,
            strategy=expert.strategy,
            raw_response=response,
            metadata={"provider": "local_transformers", "expert_id": expert.expert_id},
        )


def create_local_generator(config=None):
    model_path = os.getenv("STAGE1_STUDENT_MODEL")
    if not model_path:
        raise ValueError("Set STAGE1_STUDENT_MODEL")
    return LocalTransformersGenerator(
        model_path=model_path,
        load_in_4bit=os.getenv("STAGE1_LOAD_IN_4BIT", "true").lower() == "true",
    )
